language: objective-c
#language: ruby
#rvm:
#  - 2.0.0
before_install:
  - "which apt-get && sudo apt-get install texinfo libglib2.0-0 libglib2.0-dev libglib2.0-bin"
  - curl -L https://raw.github.com/sm/sm/master/bin/sm-installer | sh
  - export PATH="$HOME/.sm/bin:$HOME/.sm/pkg/active/bin:$PATH"
  - export CC="$( which gcc )"
install: sm ext install tokaidoapp .
before_script:
  - sm tokaidoapp dependencies
  - sm tokaidoapp packages
  - sm tokaidoapp install --without-X11 --without-tcl --without-tk
script: which ruby | grep \.sm
after_success:
  - ruby -v
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
